sudo: required
services:
  - docker

  before_install:
    - docker build -t dariusgatsby/docker-react -f Dockerfile.dev .

  script:
    - docker run -e CI=true dariusgatsby/docker-react npm run test 