sudo: required
services:
  - docker

before_install:
  - docker build -t dariusgatsby/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dariusgatsby/docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-004564996227"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  seceret_access_key: "$AWS_SECRET_KEY"